### ISSUE TITLE
Call-Flow: Aliases are not applied to visualization

### ISSUE THREAD

**Issue by mtryfoss** [sipcapture/homer-app#112]
Is there a configuration option to ignore port and only group messages by ip when drawing call flows?

**Comment by adubovikov** [comment]
you can use !5060 or !192.168.10.1 during search. The params means not equals

**Comment by lmangani** [comment]
I think an Alias for the IP with port `0` would be the approach to group w/o port distinction in general. Good occasion to cross-check.....

**Comment by mtryfoss** [comment]
Tried adding an alias, but nothing show up. No error, and no response from the request.
Any ideas? Using hom7-hep-influx docker images started up today.

{"alias":"test","ip":"10.10.10.10","port":0,"mask":32,"captureID":"1","status":true}

**Comment by mtryfoss** [comment]
Never mind my latest post. I had some network issues.

Alias is now added, but i doesn't seem to use it in the call flow?

**Comment by lmangani** [comment]
Changed the title to reflect the actual issue we should look into, hope that's alright.

**Comment by mtryfoss** [comment]
No problem. I got this error in browser console when trying to open a call too.

https://gist.github.com/mtryfoss/a41c16a9a495ea596d56927501f0344f

**Comment by negbie** [comment]
@mtryfoss Aliases are currently not implemented. The only thing you can do is to create them in the UI.

**Comment by init-0** [comment]
Any update on this?  I am in the middle of a migration to Homer 7 and this is a pretty important feature for us.

**Comment by aqsyonas** [comment]
@init-0 we are working on your request. Thank you for your patience

**Comment by charliye** [comment]
hi all, Could anyone tell me whether this bug/enhancement has been resolved?

**Comment by aqsyonas** [comment]
@charliye yes, this is fixed in below commits. 

https://github.com/sipcapture/homer-app/commit/3160b8210c6df39a3a18adce7b9059ca535f2732
https://github.com/sipcapture/homer-app/commit/d3ccc0159e081ce18069bba5cf16e8a5717b1be0

**Comment by os11k** [comment]
Hi! Does aliases should work already if I configure them in gui? I configured 2 aliases with port 5060 first and second with port 5061 and it still shows as separate servers in web...

**Comment by lmangani** [comment]
@os11k could you show us what you provisioned please?

**Comment by os11k** [comment]
Hi @lmangani sure, I just cut out 2 octets in print-screen below:
![image](https://user-images.githubusercontent.com/6322576/64699926-860e6880-d4ae-11e9-98d5-63a6e1170293.png)
