### ISSUE TITLE
Issue when adding users 

### ISSUE THREAD

**Issue by donweasel** [sipcapture/homer-app#263]
Hello,
the web-app is giving some errors when managing users. if you create one user you cant then modify any info of it, as well user settings is giving errors, see bellow

![image](https://user-images.githubusercontent.com/25114110/73302088-6c19bc00-41ea-11ea-9f45-1aa1ed3ac4ab.png)

![image](https://user-images.githubusercontent.com/25114110/73302222-a2573b80-41ea-11ea-96b5-71be6859785e.png)

**Comment by adubovikov** [comment]
I think the issue has been fixed in latest release (app+UI). Please download the package!
https://github.com/sipcapture/homer-app/releases/tag/1.1.15

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.16 Please check

**Comment by donweasel** [comment]
Hello, still having issues.
![image](https://user-images.githubusercontent.com/25114110/73480181-cbed9f80-436f-11ea-9217-ffa899a1a06f.png)

![image](https://user-images.githubusercontent.com/25114110/73480255-f2abd600-436f-11ea-8902-3a3df49ec80f.png)

**Comment by adubovikov** [comment]
I think you still use old version. How did you install it ? Packages or self compiled ?

**Comment by donweasel** [comment]
self compiled and is the latest

**Comment by adubovikov** [comment]
only homer-app or homer-ui as well ?

**Comment by adubovikov** [comment]
Please be sure that your UI is also the latest. What do you see in the browser's title ?

**Comment by donweasel** [comment]
homer app only

**Comment by adubovikov** [comment]
Ok, here is two ways - please download the latest "dist": https://github.com/sipcapture/homer-app/tree/master/dist 

or install it as package (best way)

https://github.com/sipcapture/homer-app/releases/tag/1.1.17

**Comment by donweasel** [comment]
Let me ask you if im doint it right, these how im updatting it: 

- systemctl stop heplify-server
- cd /usr/local/bin/
- rm -f homer-app
- wget https://github.com/sipcapture/homer-app/releases/download/1.1.17/homer-app
- chmod +x homer-app
- systemctl start homer-app

**Comment by lmangani** [comment]
@donweasel this should work just fine, or you could use our packages eventually to take a couple steps off

**Comment by adubovikov** [comment]
> Let me ask you if im doint it right, these how im updatting it:
> 
> * systemctl stop homer-app
> * cd /usr/local/bin/
> * rm -f homer-app
> * wget https://github.com/sipcapture/homer-app/releases/download/1.1.17/homer-app
> * chmod +x homer-app
> * systemctl start homer-app

this is only update for homer-app, but the UI still old one. the best way for you take this:

Debian:
```
wget https://github.com/sipcapture/homer-app/releases/download/1.1.17/homer-app-1.1.17-amd64.deb
dpkg -i homer-app-1.1.17-amd64.deb
systemctl start homer-app
```
Centos/RH
```
wget https://github.com/sipcapture/homer-app/releases/download/1.1.17/homer-app-1.1.17-amd64.rpm
rpm -i homer-app-1.1.17-amd64.rpm
systemctl start homer-app
```

**Comment by adubovikov** [comment]
in worse case - you can download the latest UI from here:

https://github.com/sipcapture/homer-app/tree/master/dist

**Comment by donweasel** [comment]
getting this

[root@localhost ~]# rpm -i homer-app-1.1.17-amd64.rpm
        file /usr/local/bin/homer-app from install of homer-app-1.1.17-1.x86_64 conflicts with file from package homer-app-1.1.6-1.x86_64
        file /usr/local/homer/dist/3rdpartylicenses.txt from install of homer-app-1.1.17-1.x86_64 conflicts with file from package homer-app-1.1.6-1.x86_64
        file /usr/local/homer/dist/index.html from install of homer-app-1.1.17-1.x86_64 conflicts with file from package homer-app-1.1.6-1.x86_64
        file /usr/local/homer/etc/webapp_config.json from install of homer-app-1.1.17-1.x86_64 conflicts with file from package homer-app-1.1.6-1.x86_64

**Comment by adubovikov** [comment]
rpm -U  homer-app-1.1.17-amd64.rpm

**Comment by adubovikov** [comment]
works ? Can we close the ticket?

**Comment by donweasel** [comment]
gave this, dont know if is good or bad

**Comment by donweasel** [comment]
[root@localhost ~]# systemctl status homer-app
● homer-app.service - Homer API Server and UI Webapplication
   Loaded: loaded (/usr/lib/systemd/system/homer-app.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-01-30 22:09:00 GMT; 3s ago
  Process: 11234 ExecStop=/bin/kill ${MAINPID} (code=exited, status=1/FAILURE)
  Process: 11226 ExecStart=/usr/local/bin/homer-app (code=exited, status=2)
 Main PID: 11226 (code=exited, status=2)

Jan 30 22:09:00 localhost.localdomain systemd[1]: Unit homer-app.service entered failed state.
Jan 30 22:09:00 localhost.localdomain systemd[1]: homer-app.service failed.

**Comment by adubovikov** [comment]
Please check your webapp config. Probably it was overwritten.
if you just run /usr/local/bin/homer-app ? What does it say ?

**Comment by donweasel** [comment]
yeah... it looks like

[root@localhost ~]# /usr/local/bin/homer-app
{"level":"error","msg":"pq: password authentication failed for user \"homer_user\"","time":"2020-01-30T22:42:51Z"}
panic: failed to connect database

goroutine 1 [running]:
main.getConfigDBSession(0xc00034ef20)
        /home/shurik/go/src/github.com/sipcapture/homer-app/main.go:525 +0x41b
main.main()
        /home/shurik/go/src/github.com/sipcapture/homer-app/main.go:219 +0x1ae

**Comment by adubovikov** [comment]
so, please fix your config

**Comment by donweasel** [comment]
changed the password on the config file and works good now.

the only issue i see is that when i log in with a user different than the admin i see this

![image](https://user-images.githubusercontent.com/25114110/73498985-39f88d80-4395-11ea-9892-f0e8acbb6136.png)

**Comment by s-schumann** [comment]
I had this same issue earlier (prior to the latest release) as well. Deleting the non-admin user (that was created prior to the update) and re-creating it worked after reloading the site. Maybe that helps.

**Comment by adubovikov** [comment]
unfortunately there are a small issue - now it has been fixed. Can you please take the binary and retest it ? 
https://github.com/sipcapture/homer-app/raw/master/homer-app
this issue happens only for internal non-admin users, for LDAP it worked.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.20
