### ISSUE TITLE
Loki widget not showing results

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#279]
When using the Loki search widget, I add my query and click Search which takes me to a `/call/result` URI.  The results do not show.  A scroll bar allows me to scroll up and down and the footer which shows the items and pages show the amount of returned search results.  No results are actually displayed though.

When I perform a Loki search by clicking on a call message, clicking on Logs, making sure Loki is selected, and then clicking on Refresh search.  I see the Loki results.

**Comment by AlexeyOplachko** [comment]
Happens only in Chrome, no errors in console, and data is received but is not displayed.

**Comment by RFbkak37y3kIY** [comment]
fixed on devel branch, waiting merge to master
https://github.com/sipcapture/homer-ui/commit/1c5ec6ef6b8d0f87e7a9352ed2c8ee273223ab76

**Comment by ghmj2417** [comment]
I'm still seeing this issue.  I tested this in Chrome and in Firefox and both have the same symptom.  I am pulling homer-app from master, this morning 02:37 UTC.  Is this expected or should I open this same issue under homer-ui?

**Comment by adubovikov** [comment]
Can you check the latest  UI 7.7.025? Do u see any request to the api
server?

**Comment by ghmj2417** [comment]
How does homer-ui get built when using homer-app makefile `make modules` `make all`?  It's possible I am not actually pulling in the latest homer-ui when doing the above.

Based off of what I am seeing, the UI for my build is 7.7.021 (prod).

I do see the API requests.  Data is there, results aren't being displayed.

**Comment by adubovikov** [comment]
OK... The. 021 is pretty old. Can you use packages and get the latest
version?
Or you  prefer to install manually?

**Comment by ghmj2417** [comment]
I prefer to do it manually.  Although not the best solution, I can install docker and run `make frontend` to get the latest homer-ui.  Would that work?

**Comment by adubovikov** [comment]
Clone homer-ui
Run npm install
Run npm run build

Copy dist to /usr/local/homer/dist

**Comment by ghmj2417** [comment]
Easy enough.  I'll get that done and test again.

**Comment by ghmj2417** [comment]
Tested with 7.7.025 and I don't see the issue anymore.  Thank you for pointing out the build steps for homer-ui.  When building homer-app manually is that the best way to build homer-ui?

Also, for other Loki UI issues that I am seeing, is it best to open an issue in homer-ui repo?

**Comment by adubovikov** [comment]
Yep, if you wanna do manually only, the method above is the best one

For the web part better open issues in the app repository
