### ISSUE TITLE
PNG export does not show IP addresses

### ISSUE THREAD

**Issue by hvspa** [sipcapture/homer-app#306]
i see there is anew feature there, to export the call flow as a PNG, which is great. However the exported PNG does not include the IP address in the top of the call flow tab. can you have a look into that?

thanks again :)

**Comment by adubovikov** [comment]
@RFbkak37y3kIY in the tab-flow.component.html (line 7), div alias should also have a different position during export.

**Comment by hvspa** [comment]
@RFbkak37y3kIY hi, were you able to look into this? thanks

**Comment by adubovikov** [comment]
@hvspa it's not a majior issue, therefore we will take a look once we have time for it.  If you in rush, please take a look on file tab-flow.component.html (line 7) and provide a patch

**Comment by hvspa** [comment]
> 
> 
> @hvspa it's not a majior issue, therefore we will take a look once we have time for it. If you in rush, please take a look on file tab-flow.component.html (line 7) and provide a patch

if you tell me where is it located the file you mentioning, i can definitely have a look 

i tried to search it in container, but cannot find:

docker exec -ti homer-webapp find / -name  tab-flow.component.html 2>/dev/null

also cannot attach to that container :(  cannot execute bin bash, cannot ssh :(

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-ui/blob/master/src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.html

**Comment by hvspa** [comment]
thanks Alexandr, i've had a look, but unfortunately it is above my level of knowledge :(
PS. when i open the call flow in new window and then do export to png the IPs in the title are shown in PNG.

**Comment by hvspa** [comment]
thanks Alexandr @adubovikov and Eduardo @RFbkak37y3kIY  
i want to ask you another question. in previous release, in the flow, it was also showing rtp peer IPs as well, but now it only shows signaling IPs. Do you know if it is related to settings or it is a bug? if bug where i can open an issue for this?

thanks in advance.
![Capture1](https://user-images.githubusercontent.com/27876987/77228002-b8a3c700-6b9d-11ea-8d91-f3513131a6d4.PNG)

**Comment by adubovikov** [comment]
Do you see anything in the filter ?

**Comment by hvspa** [comment]
> 
> 
> Do you see anything in the filter ?

it is just sip, but i am running the same command to send the traffic:

./heplify -hs ip:9060 -hn con

![ֆիլտեռ1](https://user-images.githubusercontent.com/27876987/77228140-b8f09200-6b9e-11ea-9653-dedbd329208d.PNG)

**Comment by adubovikov** [comment]
![Screenshot from 2020-03-21 15-09-57](https://user-images.githubusercontent.com/4513061/77228217-1af0cd80-6b86-11ea-98ae-8d9a4dc998c6.png)
just did a test - all looks ok. Do you see the rtcp reports ? Did you clean up the JS cache ?

**Comment by hvspa** [comment]
> 
> 
> ![Screenshot from 2020-03-21 15-09-57](https://user-images.githubusercontent.com/4513061/77228217-1af0cd80-6b86-11ea-98ae-8d9a4dc998c6.png)
> just did a test - all looks ok. Do you see the rtcp reports ? Did you clean up the JS cache ?

i dont see rtpc reports in the flow, but i see the qos
and no, i did not cleanup the JS cache, but i have tried on different browsers(IE, chrome, which previously never opened Homer webapp).. and the result is the same.
![qos](https://user-images.githubusercontent.com/27876987/77228460-1b4a9200-6ba1-11ea-9b87-d4fcd4db39aa.PNG)
![flow](https://user-images.githubusercontent.com/27876987/77228463-1e458280-6ba1-11ea-82a3-3b1318cf306c.PNG)

**Comment by adubovikov** [comment]
ok, we will check it on Monday. will be not bad to get the dump of your table with rtcp information (hep_proto_5)

**Comment by hvspa** [comment]
ok, thanks much. my lsql query is not responding:
homer_data=# select count(*) from  hep_proto_5_default;
:(

**Comment by adubovikov** [comment]
just do select by  callid and time range

**Comment by hvspa** [comment]
> 
> 
> just do select by callid and time range

here you go:
homer_data=# select * from  hep_proto_5_default where sid = '0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060' order by id desc;
    id    |                        sid                         |          create_date          |                                                                                                                                                   protocol_header                                                                                                                                                   |                data_header                |                                                                                                                                                                                                                                                                              raw                                                                                                                                                                                                                                                                               
----------+----------------------------------------------------+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 44667520 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:21:03.599943+00 | {"dstIp": "10.211.46.16", "srcIp": "10.211.46.28", "dstPort": 17301, "srcPort": 12079, "protocol": 17, "captureId": "con", "payloadType": 5, "timeSeconds": 1584800463, "timeUseconds": 599942, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2}               | {"node": "con", "proto": "rtcp"} | {"sender_information":{"ntp_timestamp_sec":3793789262,"ntp_timestamp_usec":3198273024,"rtp_timestamp":119728,"packets":548,"octets":87680},"ssrc":476556296,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":1047800776,"fraction_lost":0,"packets_lost":0,"highest_seq_no":2184,"ia_jitter":9,"lsr":2706021714,"dlsr":326762}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":476556296}
 44667421 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:21:03.600041+00 | {"dstIp": "10.211.46.28", "srcIp": "10.211.46.16", "dstPort": 12079, "srcPort": 17301, "protocol": 17, "captureId": "con", "payloadType": 5, "timeSeconds": 1584800463, "timeUseconds": 600041, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2}               | {"node": "con", "proto": "rtcp"} | {"sender_information":{"ntp_timestamp_sec":3793789263,"ntp_timestamp_usec":2638673152,"rtp_timestamp":119317,"packets":504,"octets":79965},"ssrc":1047800776,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":476556296,"fraction_lost":0,"packets_lost":0,"highest_seq_no":9752,"ia_jitter":0,"lsr":2705964703,"dlsr":326238}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":1047800776}
 44667416 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:21:02.79783+00  | {"dstIp": "10.211.46.16", "srcIp": "10.211.46.28", "dstPort": 17301, "srcPort": 12079, "protocol": 17, "captureId": "1234", "capturePass": "foo", "payloadType": 5, "timeSeconds": 1584800462, "timeUseconds": 797829, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2} | {"node": "1234", "proto": "rtcp"}         | {"ssrc":3793789262,"type":200,"report_count":1,"sender_information":{"ntp_timestamp_sec":"1584800462","ntp_timestamp_usec":"744655","rtp_timestamp":119728,"packets":548,"octets":87680},"report_blocks":[{"source_ssrc":1047800776,"fraction_lost":0,"packets_lost":0,"highest_seq_no":2184,"ia_jitter":9,"lsr":"2706021714","dlsr":326762}]}
 44667385 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:21:02.736918+00 | {"dstIp": "10.211.46.28", "srcIp": "10.211.46.16", "dstPort": 12079, "srcPort": 17301, "protocol": 17, "captureId": "1234", "capturePass": "foo", "payloadType": 5, "timeSeconds": 1584800462, "timeUseconds": 736918, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2} | {"node": "1234", "proto": "rtcp"}         | {"ssrc":1047800776,"type":200,"report_count":1,"sender_information":{"ntp_timestamp_sec":"1584800463","ntp_timestamp_usec":"614364","rtp_timestamp":119317,"packets":504,"octets":79965},"report_blocks":[{"source_ssrc":476556296,"fraction_lost":0,"packets_lost":0,"highest_seq_no":9752,"ia_jitter":0,"lsr":"2705964703","dlsr":326238}]}
 44667281 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:20:58.590052+00 | {"dstIp": "10.211.46.28", "srcIp": "10.211.46.16", "dstPort": 12079, "srcPort": 17301, "protocol": 17, "captureId": "con", "payloadType": 5, "timeSeconds": 1584800458, "timeUseconds": 590051, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2}               | {"node": "con", "proto": "rtcp"} | {"sender_information":{"ntp_timestamp_sec":3793789258,"ntp_timestamp_usec":2639437696,"rtp_timestamp":79691,"packets":353,"octets":56075},"ssrc":1047800776,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":476556296,"fraction_lost":0,"packets_lost":0,"highest_seq_no":9527,"ia_jitter":0,"lsr":2705636995,"dlsr":324272}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":1047800776}
 44667263 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:20:58.590037+00 | {"dstIp": "10.211.46.16", "srcIp": "10.211.46.28", "dstPort": 17301, "srcPort": 12079, "protocol": 17, "captureId": "con", "payloadType": 5, "timeSeconds": 1584800458, "timeUseconds": 590037, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2}               | {"node": "con", "proto": "rtcp"} | {"sender_information":{"ntp_timestamp_sec":3793789257,"ntp_timestamp_usec":3198109824,"rtp_timestamp":51520,"packets":322,"octets":51520},"ssrc":476556296,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":1047800776,"fraction_lost":0,"packets_lost":0,"highest_seq_no":2033,"ia_jitter":0,"lsr":2705693998,"dlsr":324796}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":476556296}
 44667259 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:20:57.758972+00 | {"dstIp": "10.211.46.16", "srcIp": "10.211.46.28", "dstPort": 17301, "srcPort": 12079, "protocol": 17, "captureId": "1234", "capturePass": "foo", "payloadType": 5, "timeSeconds": 1584800457, "timeUseconds": 758971, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2} | {"node": "1234", "proto": "rtcp"}         | {"ssrc":3793789257,"type":200,"report_count":1,"sender_information":{"ntp_timestamp_sec":"1584800457","ntp_timestamp_usec":"744617","rtp_timestamp":51520,"packets":322,"octets":51520},"report_blocks":[{"source_ssrc":1047800776,"fraction_lost":0,"packets_lost":0,"highest_seq_no":2033,"ia_jitter":0,"lsr":"2705693998","dlsr":324796}]}
 44667190 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:20:57.73721+00  | {"dstIp": "10.211.46.28", "srcIp": "10.211.46.16", "dstPort": 12079, "srcPort": 17301, "protocol": 17, "captureId": "1234", "capturePass": "foo", "payloadType": 5, "timeSeconds": 1584800457, "timeUseconds": 737210, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2} | {"node": "1234", "proto": "rtcp"}         | {"ssrc":1047800776,"type":200,"report_count":1,"sender_information":{"ntp_timestamp_sec":"1584800458","ntp_timestamp_usec":"614542","rtp_timestamp":79691,"packets":353,"octets":56075},"report_blocks":[{"source_ssrc":476556296,"fraction_lost":0,"packets_lost":0,"highest_seq_no":9527,"ia_jitter":0,"lsr":"2705636995","dlsr":324272}]}
 44667126 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:20:53.580185+00 | {"dstIp": "10.211.46.28", "srcIp": "10.211.46.16", "dstPort": 12079, "srcPort": 17301, "protocol": 17, "captureId": "con", "payloadType": 5, "timeSeconds": 1584800453, "timeUseconds": 580184, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2}               | {"node": "con", "proto": "rtcp"} | {"sender_information":{"ntp_timestamp_sec":3793789253,"ntp_timestamp_usec":2637079680,"rtp_timestamp":39282,"packets":198,"octets":31410},"ssrc":1047800776,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":476556296,"fraction_lost":0,"packets_lost":0,"highest_seq_no":9453,"ia_jitter":0,"lsr":0,"dlsr":0}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":1047800776}
 44667007 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:20:53.580202+00 | {"dstIp": "10.211.46.16", "srcIp": "10.211.46.28", "dstPort": 17301, "srcPort": 12079, "protocol": 17, "captureId": "con", "payloadType": 5, "timeSeconds": 1584800453, "timeUseconds": 580202, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2}               | {"node": "con", "proto": "rtcp"} | {"sender_information":{"ntp_timestamp_sec":3793789252,"ntp_timestamp_usec":3196306048,"rtp_timestamp":39680,"packets":248,"octets":39680},"ssrc":476556296,"type":202,"report_count":1,"report_blocks":[{"source_ssrc":1047800776,"fraction_lost":0,"packets_lost":0,"highest_seq_no":1878,"ia_jitter":8,"lsr":0,"dlsr":0}],"report_blocks_xr":{"type":0,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":0,"round_trip_delay":0,"end_system_delay":0},"sdes_ssrc":476556296}
 44666956 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:20:52.788674+00 | {"dstIp": "10.211.46.16", "srcIp": "10.211.46.28", "dstPort": 17301, "srcPort": 12079, "protocol": 17, "captureId": "1234", "capturePass": "foo", "payloadType": 5, "timeSeconds": 1584800452, "timeUseconds": 788673, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2} | {"node": "1234", "proto": "rtcp"}         | {"ssrc":3793789252,"type":200,"report_count":1,"sender_information":{"ntp_timestamp_sec":"1584800452","ntp_timestamp_usec":"744197","rtp_timestamp":39680,"packets":248,"octets":39680},"report_blocks":[{"source_ssrc":1047800776,"fraction_lost":0,"packets_lost":0,"highest_seq_no":1878,"ia_jitter":8,"lsr":"0","dlsr":0}]}
 44666935 | 0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060 | 2020-03-21 14:20:52.736688+00 | {"dstIp": "10.211.46.28", "srcIp": "10.211.46.16", "dstPort": 12079, "srcPort": 17301, "protocol": 17, "captureId": "1234", "capturePass": "foo", "payloadType": 5, "timeSeconds": 1584800452, "timeUseconds": 736687, "correlation_id": "0e8973e14e7e52a178c0e16371ee5b8a@10.211.46.16:5060", "protocolFamily": 2} | {"node": "1234", "proto": "rtcp"}         | {"ssrc":1047800776,"type":200,"report_count":1,"sender_information":{"ntp_timestamp_sec":"1584800453","ntp_timestamp_usec":"613993","rtp_timestamp":39282,"packets":198,"octets":31410},"report_blocks":[{"source_ssrc":476556296,"fraction_lost":0,"packets_lost":0,"highest_seq_no":9453,"ia_jitter":0,"lsr":"0","dlsr":0}]}
(12 rows)

homer_data=#

**Comment by hvspa** [comment]
Hi Alexandr,

Just wanted to ask you if you had a chance to look at this issue with RTP flow?

**Comment by hvspa** [comment]
hi Alexandr,

did you have chance to look into this issue? i am still wondering what i am missing to show RTP payload type? it is only showing SIP payload, but the data is in database as per above queries

**Comment by adubovikov** [comment]
please check the latest UI. It should be fixed

**Comment by hvspa** [comment]
> please check the latest UI. It should be fixed

i installed the docker homer 7.8.1 prod from scratch yesterday, and still having the same issue.
i believe it is some configuration issue, and will appreciate if we can figure it out together... 

again it was present before i upgraded as mentioned in one of my comments

**Comment by adubovikov** [comment]
I think the latest version is not in the docker yet. @mikegoodstadt can you please check here ?

**Comment by lmangani** [comment]
@adubovikov @mikegoodstadt the containers are build as normal from master every night, same logic/cycle as package releases.

**Comment by hvspa** [comment]
is it possible that the problem is the select query? maybe the search query should be changed or some settings are not done correctly?

**Comment by hvspa** [comment]
> 
> 
> @adubovikov @mikegoodstadt the containers are build as normal from master every night, same logic/cycle as package releases.

yesterday, i removed everything, all the volumes, all the images, all the containers and all data, and started installation of docker homer from zero:
git clone https://github.com/sipcapture/homer7-docker.git 
cd ...path
docker-compose -f docker-compose.yml up -d

but the issue is still there. i dont see RTP endpoints in the flow. not sure if i am doing something wrong or some config is missing from somewhere... 
can you suggest?

**Comment by AlexeyOplachko** [comment]
Hi @hvspa can you please send us copy of "transaction" and "QOS" requests and responses from Chrome Dev tools from the call with this issue? It might be related to issue we partially fixed, but not merged into master yet.

**Comment by hvspa** [comment]
> 
> 
> Hi @hvspa can you please send us copy of "transaction" and "QOS" requests and responses from Chrome Dev tools from the call with this issue? It might be related to issue we partially fixed, but not merged into master yet.

hi Alexey, and thanks for quick turnaround.  i am not sure i know how to do that. i am using FF as a browser. if you can tell me what to do step by step, i can quickly do that now and send you required info

**Comment by AlexeyOplachko** [comment]
1. Open devtools with F12
2. Switch to tab "Network"
3. Open a call with this issue
4. Find lines that say "POST domain transaction", click on it. You'll see small submenu open on the right
5. Switch to "Request" tab in that submenu
6. Copy into some txt file from "Request payload"
7. Switch to "Response" tab in that submenu
8. Copy into same file from "Response payload"
9. Repeat actions 5 - 8 with line "POST domain QOS"

**Comment by hvspa** [comment]
> 
> 
> Instructions for FF
> 
>     1. Open devtools with F12
> 
>     2. Switch to tab "Network"
> 
>     3. Open a call with this issue
> 
>     4. Find line that says "POST domain transaction", click on it. You'll see small submenu open on the right
> 
>     5. Switch to "Request" tab in that submenu
> 
>     6. Copy into some txt file from "Request payload"
> 
>     7. Switch to "Response" tab in that submenu
> 
>     8. Copy into same file from "Response payload"
> 
>     9. Repeat actions 5 - 8 with line "POST domain QOS"

thanks much, see attached file
[requested info.zip](https://github.com/sipcapture/homer-app/files/5042151/requested.info.zip)

Maracana1#

**Comment by hvspa** [comment]
hi ALexey, did you have chance to look into the logs i provided?

**Comment by AlexeyOplachko** [comment]
Hi @hvspa, yes, we're working on a fix :)

**Comment by hvspa** [comment]
ok, cool, thanks much for update Alexey. appreciate your quick help

**Comment by adubovikov** [comment]
did it fix in the last devel ?

**Comment by hvspa** [comment]
> 
> 
> did it fix in the last devel ?

thanks very much Alexandr for follow up.

i just checked and IPs are now shown while exporting to PNG.

thanks again and have a great evening.

**Comment by adubovikov** [comment]
Perfect! I will close the issue. Thank for patience!
