### ISSUE TITLE
homer7 flow tab is not merging aliases

### ISSUE THREAD

**Issue by lazedo** [sipcapture/homer-app#310]
in homer5 we created aliases for servers with multiple ports and the flow would show that server only once. in homer7 (homer7-docker branch 7.7), with the same aliases created, the flow shows the alias of the server correctly but it shows the same server several times depending on the ports involved in the transaction

**Comment by kpribic** [comment]
+1

This can get pretty annoying when using TCP because ports can change within one dialog.

Maybe it would make sense to merge aliases when ports are turned off via the (great!) new feature in homer-ui. This way we could have the cake and eat it, if you want to see merged aliases then turn off ports, if you wan't to see everything - just keep the ports displayed.

**Comment by lazedo** [comment]
ports turned off would simplify it but would not work me in this case, i have some ports for kamailio and other ports for freeswitch. this works great in home5

**Comment by runelucica** [comment]
Jumping on this one as well, as I read something that caught my attention.
I am also struggling with defining Aliases in such way where if I have multiple ports and one host I would like that to appear once or max 2 times (once for signaling and once for media).
Is there anyway you can add a port range? I tried but it gave an error.

@kpribic - I just tried the port turn off feature and it does not update the Alias in the Flow tab for the same host with the non-defined port.
Does this work for you? I have one Alias created that matches the signaling part and the same host (with a diff port) is also part of the conversation for media. However when I uncheck the Display Port.

**Comment by kpribic** [comment]
> @kpribic - I just tried the port turn off feature and it does not update the Alias in the Flow tab for the same host with the non-defined port.
> Does this work for you? I have one Alias created that matches the signaling part and the same host (with a diff port) is also part of the conversation for media. However when I uncheck the Display Port.

No, I don't think that works now, I was just suggesting that it would be a good way to implement merging while retaining the option to see separate ports (which can be useful).

**Comment by runelucica** [comment]
Not sure if anyone else answered this one, but I was reading some older issues and found that by setting the Port value to 0 will allow the same Alias label to be applied in the Flow tab (even if the Port is different).

Hope this helps someone.

**Comment by runelucica** [comment]
This is however different from the request above.
I read it again :). Does not really in that case.

**Comment by lmangani** [comment]
@runelucica the port 0 behaviour is exactly as per design. Match all/any ports for an IP.

**Comment by runelucica** [comment]
Understood. Did not know this, so I was happy to find that out.
Should configuring port 0 for an Alias display that host only once in the Flow tab or only show the Alias multiple times (if same IP with diff ports is used)?

This is how I have configured an Alias:

![Alias](https://user-images.githubusercontent.com/41921868/76317707-e440ca80-62dc-11ea-8be7-ac9909f0075c.PNG)

And this is how the flow looks like:

![Flow](https://user-images.githubusercontent.com/41921868/76317752-f4f14080-62dc-11ea-9a89-d8a1ed8571b6.PNG)

As you can see TESTIPTVM01 appears twice in the flow because of the different ports being used.
Is this behavior as per design?

**Comment by runelucica** [comment]
@lmangani Could you please let us know if the above (not merging all instances of the same Alias in the Flow tab) works as per design or should we expect a different behavior?

**Comment by khorsmann** [comment]
I saw this also (not merging aliases) if i wrote the same alias name with diffrent ips, it was merged in homer-5

**Comment by lmangani** [comment]
@AlexeyOplachko could you check if this is still unresolved?

**Comment by RFbkak37y3kIY** [comment]
implemented on DEVEL branch, waiting to merge to master branch.
https://github.com/sipcapture/homer-ui/commit/98ffe1dd21b8dfc4463e5a50f8d913d0d4fd767f
https://github.com/sipcapture/homer-ui/commit/a1be93bef5d7543a23eeed1b66444928adfe7d06
https://github.com/sipcapture/homer-ui/commit/8dea1e5fc20b03c1da8f2246f2672495c627595c
https://github.com/sipcapture/homer-ui/commit/518cbf97d3fe94485fe0221c4190e69a99521ecf

**Comment by systemcrash** [comment]
Not that I like to throw spanners in the works all the time, but I hope these fixes take into account IPv6. Aliases sort of work with IPv6 at the moment. 


 IPv6 | fd89:b146:7dc:c425::/64
-- | --

I'm guessing, but I assume the column 'mask' in the table means 'network mask'? If so, it does not work to e.g. provide a 128 bit IPv6 and set mask to 64 or higher. Technically it should be 128 for a single IPv6 - but leaving it at 32 works for a single IPv6. Set it to 64, and any IP in the 64 bit subnet does not get 'aliased'. 

There are good js libs out there for IP handling. If you don't want requirements, convert an IP to an int and bitshift or truncate.

**Comment by mikegoodstadt** [comment]
Thanks Paul for the input - and not at all a spanner in the works :) We have been working on an update covering this during the last week (and taking on board you comments in homer-ui issue #240 re. Sort by src/dst IP). Aim to finalize shortly.

**Comment by mikegoodstadt** [comment]
[Fixed in commit: fix: IPv6 with Combine Aliases & Show/hide ports](https://github.com/sipcapture/homer-ui/commit/2ac1f748e93828f7d2f8b7c24d61355dad8d9402)

**Comment by systemcrash** [comment]
I assume you meant https://github.com/sipcapture/homer-ui/issues/240 for IP sorting :)

**Comment by vaizki** [comment]
Thank you for this, I just updated to the :latest docker image and things are better. However I'm still seeing some situations like this:

![image](https://user-images.githubusercontent.com/5273623/87055302-d3618080-c20c-11ea-9480-4e89c73abc8f.png)

Here 10.251.8.10 has an alias with port = 0 but it still shows as two entities in the flow. The communication is over TLS so I am using the siptrace module in Kamailio 5.3 to send HEP packets to homer.

**Comment by adubovikov** [comment]
@viazi , if you click on the filter and try to merge the hosts, does it solve the issue ?

**Comment by vaizki** [comment]
> @viazi , if you click on the filter and try to merge the hosts, does it solve the issue ?

@adubovikov, actually it does when I select Group by Alias from the filter. Thank you! Somehow I missed the whole filter-menu, sorry for the false alarm.

I am seeing some issues with de-dup'ing now but I don't think they are related to this so will investigate them separately.

**Comment by mikegoodstadt** [comment]
Good to hear!
