### ISSUE TITLE
Not able to visualize the REGISTER SIP Method traces in Homer webapp

### ISSUE THREAD

**Issue by ishvaram** [sipcapture/homer-app#382]
By default, Call traces only coming in the UI and I'm able to see traces. But not the call registration traces. I see the registration traces are present in my DB and also homer reads from hep_proto_1_call and not from hep_proto_1_registration.

How can I include hep_proto_1_registration also and visualize the REGISTER SIP Method also?

Also, I'm not able to save any of the mappings json data, after saving it throws below error 
![sdsdsdsds](https://user-images.githubusercontent.com/4301774/92309615-b3f49300-efc4-11ea-9c0b-71b8c5c7b215.png)

Homer Login page taking too much time to load? any workaround for these issues?

**Comment by adubovikov** [comment]
You have to create a new widget and as profile select SIP -> registration

**Comment by adubovikov** [comment]
about Homer Login page - not sure I understood your question well. If you can provide more details - we can give you an advice

**Comment by adubovikov** [comment]
I hope the issue has been solved. Please come back if you will have more details

**Comment by ishvaram** [comment]
@adubovikov issue is not yet resolved. I'm not able to edit the Fields Mapping still. I've added the screenshot as well where the error message is shown.

**Comment by ishvaram** [comment]
And i'm still not able to visualize the flow graph in the web app. I see the below exception in developer console
![registeruknownerror](https://user-images.githubusercontent.com/4301774/92558086-5ba2e700-f28b-11ea-8a39-e5e07f1f5d22.png)

**Comment by adubovikov** [comment]
I am not sure that are you doing. As I see you have REGISTER result and what do you need else - for me it's unclear :-(
Please be more concrete and don't forget, this is open source project and if you need HELP, you have to be ready provide details and be patient.

**Comment by ishvaram** [comment]
@adubovikov Sorry for the not fully constructed message. 

on clicking the Session ID and I'm expecting to see the visualization REGISTER flow request coming from the client IP to our Server. just like below

https://3.bp.blogspot.com/-9A7SeUiQKyg/UgyQrdW7WJI/AAAAAAAAFxo/cBshWfuIuEE/s1600/sip+register+call+flow.png

**Comment by adubovikov** [comment]
@ishvaram as I mentioned above, you have to check your api query and be sure you receive a reply with data from your API. And again, you have to be more construtive - just saying "doesn't work" helps absolutely nothing

**Comment by ishvaram** [comment]
@adubovikov I'm attaching the GIF image for the issue reference . Not sure in what other words I should explain the issue. 
![captured (4)](https://user-images.githubusercontent.com/4301774/92592894-e13f8a80-f2bd-11ea-85ef-e3cfb866bfe8.gif)

Upon clicking the REGISTER i see the blank pop-up for SIP flow visualization.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Troubleshooting-Homer-7.7#debug-in-web-console

**Comment by adubovikov** [comment]
you have to use debug in web console the Network tab and see if you have any data in the api response

**Comment by ishvaram** [comment]
@adubovikov SIP flow visualization for the call is working for me. but not for the REGISTER flow and I could able to see the data in each event when I click on the SIP method. But when I click on the Session ID pop up comes but empty. As you suggested i saw the browser console's Network tab response , below is the response
```
{"data":{"alias":{},"calldata":[],"hosts":{},"messages":[]},"keys":[],"total":0}
```
Like I mentioned earlier each of SIP METHOD data I'm able to see when clicking any of the SIP method column values like REGISTER, 200, 401 in the pop up and console data is coming
![captured (6)](https://user-images.githubusercontent.com/4301774/92622375-94ba7600-f2e2-11ea-866d-c820def4c12f.gif)

and but when I click the Session ID the pop shows nothing and the console element data is empty.


Any suggestions on what could be the issue?

**Comment by adubovikov** [comment]
this means something wrong and the homer-app doesn't return data to you. After how much seconds did  you received the final answer from the homer-app ? You can see it in waterfall . 

I have just checked fresh install - all looks good. This is indeded an issue on your setup. Try to activate debug in the homer-app
and see the query that the app has been sent to postgress. Try to reduce the time range.

**Comment by ishvaram** [comment]
@adubovikov i see the data is coming from psql, but homer-app not able to render it in the UI.


```
{"HOST":"homer.exotel.in","METHOD":"GET","PATH":"/api/v3/advanced","QueryParam":"","level":"info","msg":"Request","time":"2020-09-11T09:51:06+05:30"}

{"level":"info","msg":"-------- response body --------","time":"2020-09-11T09:51:06+05:30"}
{"json":"\u001f\ufffd\u0008\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffdn\ufffd \u0014\ufffd\ufffd{9k#3\ufffd\u0000\ufffdl\ufffd\u000e7Puq\ufffd\u0010[i\ufffd\u00058U\u0015\ufffd\ufffd++\u001d\ufffde\ufffd-\ufffd\ufffd\ufffd;\ufffdK\ufffdT\ufffd\ufffd\u0006\u003cV\u0004\ufffdp\u0004\ufffd5lS~\u0001\u000b%`v\u0003\ufffd_\u001eaH\ufffd\ufffd\ufffd\ufffd\ufffdٶ\ufffdSڍV0J\ufffd\ufffd\ufffdv\u0019=X\ufffdN\ufffd\ufffdb$\ufffd\u0005E$\ufffdz\ufffd\u000b\ufffd\ufffdcO\ufffd\ufffd^u\ufffdC\u00033f܃\ufffd5QB\u003e\ufffd|\u003e\ufffdk\ufffd\ufffd\ufffd\ufffd0\ufffd\ufffd\ufffd\ufffd\u000ea)\ufffdPC[\ufffd\ufffd\ufffd\ufffd\ufffd\u000bT\ufffd\ufffd\ufffdh\u0017\ufffdЎ\u0013I\u0019%ڣ#\ufffd\ufffd\ufffdG\u0026\ufffd\ufffd\ufffd\u0002\ufffd\u0006\ufffd\ufffdf\ufffd8\ufffd\u0015\ufffd\ufffdӥ\u003c\ufffd\ufffdb\ufffd\ufffd\ufffd\t\u001a\ufffdi\u0017\u0026\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd_]\ufffd\ufffd\ufffd\ufffdC\u0003K\t\ufffd\ufffd\ufffd\ufffd\u0004\u0011\u000c:\u001d#Q\ufffdk\"\r\ufffd\u0004\ufffd\u000cDmz\ufffdX\ufffd\u0004Fu1\ufffd\ufffd\ufffd/\ufffd\ufffd\ufffdk\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffd\ufffd4\ufffd\u0001\u0000\u0000","level":"info","msg":"Payload","time":"2020-09-11T09:51:06+05:30"}
{"level":"info","msg":"-------------------------------","time":"2020-09-11T09:51:06+05:30"}
{"level":"info","msg":"=================================","time":"2020-09-11T09:51:06+05:30"}
```

**Comment by ishvaram** [comment]
@adubovikov I'm using the branch go since master doesn't have dist. Is something wrong in here?

**Comment by ishvaram** [comment]
@adubovikov Checked out a tag 1.1.8 and rebuilt homer-app it works now.

**Comment by adubovikov** [comment]
glad that you solved it. If you don't use packages, please always compile the dist
